### ISSUE TITLE
#26 getFee() calculates with floating value

### ISSUE THREAD

**Issue by Dawn-githup** [ckb-cell/rgbpp-sdk#29] opened 2024-03-19 08:15 UTC
![image](https://github.com/ckb-cell/rgbpp-sdk/assets/77844990/45e6e4b3-31ea-43eb-b6c7-604da0a15dfb)

**Comment by Dawn-githup** [comment] 2024-03-19 08:20
##### txid：https://mempool.space/testnet/tx/c011d6f5ce04497cbb1365dac4f4bce50ffd71bd7b4710520e13ad738d3533be

##### Verification scenario：
Transfer fixed UTXO, sum(ins) = sum(outs)

fee is calculated as a floating value

error:
```
Error:BtcAssetSAPIreturned an error:.(-26)min relay fee not met, 208 < 209
```

**Comment by ShookLyngs** [comment] 2024-03-26 11:42
This issue was supposed to be fixed at, which you can refer to: https://github.com/ckb-cell/rgbpp-sdk/commit/9482f6c0d93e4424bcb7518846edd8945fd2c798#diff-9f6a20e068a71d2b7153282a3fc01fae60be3f1a0562523c903b50a36a4279fdR302

What I changed in the commit was that I added a `inputs.length` when summing the weight of the transaction:
```ts
-const weight = weightWithoutWitness * 3 + weightWithWitness;
+const weight = weightWithoutWitness * 3 + weightWithWitness + inputsLength;
```

Although I'm still not 100% sure that the issue is fixed, it should make a difference as the fee is definitely enough if each input's witness can only be 1 byte smaller than it should be (the stats says it usually needs 0.5 byte more, so adding 1 byte should be reasonable). Can you guys review the fee estimation code with me?

**Comment by ShookLyngs** [comment] 2024-04-19 02:19
We have not received any reports about the issue since the previous comment. 
I think it's safe to say the issue is resolved, therefore I'm closing it.

**Closed by ShookLyngs** 2024-04-19 02:19 UTC
Labels: P-Medium
